### ISSUE TITLE
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

### ISSUE THREAD

**Issue by manuelmontesinos** [florafauna/optimParallel-python#8]
Hello,

I have tried to use the package in Python 2.7.18, macOS Monterey 12.0.1, to run the following code that minimizes a function and keeps track of the computing time:
```python
# Import modules
import numpy as np
import timeit
from scipy.optimize import minimize
from optimparallel import minimize_parallel

# Define the function
def objective(x):
    return x[0]**2.0 + x[1]**2.0

# Define the range for input
r_min , r_max = -5.0, 5.0

# Define the starting point as a random sample from the domain
pt = r_min + np.random.rand(2)*(r_max - r_min)

# Minimize the function
start = timeit.default_timer()
resultpar = minimize_parallel(fun=objective, x0=pt)
finish = timeit.default_timer()
print('Finished in', round(finish-start, 2), 'second(s)')
```

However, Python issues this error when I try to execute this script:
```
Traceback (most recent call last):
  File "/Users/montesinos/opt/anaconda3/envs/gambit/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
Traceback (most recent call last):
  File "/Users/montesinos/opt/anaconda3/envs/gambit/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
Traceback (most recent call last):
  File "/Users/montesinos/opt/anaconda3/envs/gambit/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

According to [what I read](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function), it seems that Python cannot pass the function to the worker processes. Does anyone know what could be happening?

**Comment by ghost** [comment]
That's an issue with `pickle` on MacOS. Try to write your own executor using `dill` or `pathos` and pass it into the function at `parallel["executor"]`

**Comment by florafauna** [comment]
The package is not tested with Python 2.7.x.
